//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace topic
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarePair
    {
        public System.Guid ID { get; set; }
        public System.Guid CaregiverID { get; set; }
        public System.Guid CareRecipientID { get; set; }
    
        public virtual Caregiver Caregiver { get; set; }
        public virtual CareRecipient CareRecipient { get; set; }
    }
}
