//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace topic
{
    using System;
    using System.Collections.Generic;
    
    public partial class EquipmentContainType
    {
        public System.Guid ID { get; set; }
        public System.Guid EquipmentID { get; set; }
        public System.Guid EquipmentTypeID { get; set; }
    
        public virtual Equipment Equipment { get; set; }
        public virtual EquipmentType EquipmentType { get; set; }
    }
}
