//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace topic
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fall
    {
        public System.Guid ID { get; set; }
        public System.DateTime DateTime { get; set; }
        public System.Guid EquipmentID { get; set; }
        public bool isChecked { get; set; }
        public Nullable<System.Guid> CaregiverID { get; set; }
        public Nullable<System.DateTime> CheckDateTime { get; set; }
    
        public virtual Caregiver Caregiver { get; set; }
        public virtual Equipment Equipment { get; set; }
    }
}
