//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace topic
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TopicEntities : DbContext
    {
        public TopicEntities()
            : base("name=TopicEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BloodPressure> BloodPressures { get; set; }
        public virtual DbSet<Caregiver> Caregivers { get; set; }
        public virtual DbSet<CarePair> CarePairs { get; set; }
        public virtual DbSet<CareRecipient> CareRecipients { get; set; }
        public virtual DbSet<Equipment> Equipments { get; set; }
        public virtual DbSet<EquipmentType> EquipmentTypes { get; set; }
        public virtual DbSet<Fall> Falls { get; set; }
        public virtual DbSet<Humidity> Humidities { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Temperature> Temperatures { get; set; }
        public virtual DbSet<EquipmentContainType> EquipmentContainTypes { get; set; }
        public virtual DbSet<BloodOxygen> BloodOxygens { get; set; }
        public virtual DbSet<HeartRate> HeartRates { get; set; }
    }
}
